### PR TITLE
Repository Improvements

### PR DESCRIPTION
**Pull request by GrahamCampbell**
// cc @joecohens

### CODE REVIEW

**Comment by joecohens** [comment]
:+1: :+1: Clean !! And also easy to implement Bitbucket next :)

**Comment by joecohens** [comment]
Also loved the PersistentRepository and attempts :)

**Comment by GrahamCampbell** [comment]
> And also easy to implement Bitbucket next :)

lol, bitbucket should be the same, I'd just need to change the url. The bitbucket integration would be a pain in the main styleci repo. I don't plan to actually implement it at the moment.

> Also loved the PersistentRepository and attempts :)

Yeh, I need to be 1000% sure I've got the logic correct there. :)

**Comment by joecohens** [comment]
> Yeh, I need to be 1000% sure I've got the logic correct there. :)

How can we test it?

**Comment by GrahamCampbell** [comment]
By deploying it, lol.

**Comment by GrahamCampbell** [comment]
And then I'll delete a .git folder in one of the cached repos and see if everything explodes, or if it quitely deletes it and clones it again.

**Comment by joecohens** [comment]
LOL :8ball:

**Comment by GrahamCampbell** [comment]
Meh, I'll merge this and then abstract it to another package. Then I'll deploy it to test it out. :)

**Comment by joecohens** [comment]
:) Prefect!

**Comment by GrahamCampbell** [comment]
@joecohens https://github.com/StyleCI/Fixer/compare/119f7a79b50a338f0da541e721601e7d76dbe3e5...ca3d9a26e37ed05fb1f0e82d29d5cb86ba9dd8c0, https://github.com/StyleCI/Git.

**Comment by GrahamCampbell** [comment]
The next deploy I do is going to be super risky. Also, styleci will go down for an undefined number of mins, so be warned. Hopefully, it will only be a few seconds, but I have no idea if any of this stuff works, lol.

**Comment by GrahamCampbell** [comment]
Nothin' like testing something for the first time in production. :)

**Comment by GrahamCampbell** [comment]
Well, the website is back in production now. Now time to turn on the queue processing and try to break it. :)

**Comment by joecohens** [comment]
:boom:

**Comment by joecohens** [comment]
LOL testing in production = pure adrenaline :)

**Comment by GrahamCampbell** [comment]
I broke it...

**Comment by joecohens** [comment]
:(

**Comment by GrahamCampbell** [comment]
i've suspended job processing for now...

**Comment by joecohens** [comment]
Do you have logs?

**Comment by GrahamCampbell** [comment]
Yeh, that's why I killed the job processor. Otherwise end up with 100gb log files...

**Comment by GrahamCampbell** [comment]
```
exception 'StyleCI\Git\Exceptions\Persistence\CloningRepositoryException' with message 'Cloning the repository has failed.' in /web/graham/styleci/vendor/styleci/git/src/Repositories/PersistentRepository.php:99
Stack trace:
#0 /web/graham/styleci/vendor/styleci/fixer/src/Fixer.php(106): StyleCI\Git\Repositories\PersistentRepository->get()
#1 /web/graham/styleci/vendor/styleci/fixer/src/Fixer.php(74): StyleCI\Fixer\Fixer->setup(Object(StyleCI\Git\Repositories\PersistentRepository), 'cea18a38ce7755a...')
#2 /web/graham/styleci/app/Analyser.php(111): StyleCI\Fixer\Fixer->analyse('StyleCI/Git', 'cea18a38ce7755a...')
#3 /web/graham/styleci/app/Tasks/Analyse.php(54): StyleCI\StyleCI\Analyser->runAnalysis(Object(StyleCI\StyleCI\Models\Commit))
#4 /web/graham/styleci/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(96): StyleCI\StyleCI\Tasks\Analyse->fire(Object(Illuminate\Queue\Jobs\DatabaseJob), Object(StyleCI\StyleCI\Models\Commit))
#5 /web/graham/styleci/vendor/laravel/framework/src/Illuminate/Queue/Jobs/DatabaseJob.php(48): Illuminate\Queue\Jobs\Job->resolveAndFire(Array)
#6 /web/graham/styleci/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(206): Illuminate\Queue\Jobs\DatabaseJob->fire()
#7 /web/graham/styleci/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(158): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), '0', '0')
#8 /web/graham/styleci/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(107): Illuminate\Queue\Worker->pop(NULL, 'default', '0', '5', '0')
#9 /web/graham/styleci/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(67): Illuminate\Queue\Console\WorkCommand->runWorker(NULL, 'default', '0', '128', false)
#10 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#11 /web/graham/styleci/storage/framework/compiled.php(411): call_user_func_array(Array, Array)
#12 /web/graham/styleci/vendor/laravel/framework/src/Illuminate/Console/Command.php(112): Illuminate\Container\Container->call(Array)
#13 /web/graham/styleci/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /web/graham/styleci/vendor/laravel/framework/src/Illuminate/Console/Command.php(100): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /web/graham/styleci/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /web/graham/styleci/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /web/graham/styleci/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /web/graham/styleci/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(90): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /web/graham/styleci/artisan(43): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 {main}
```

**Comment by joecohens** [comment]
Wow 100gb!!

**Comment by GrahamCampbell** [comment]
Not yet, lol. It's only 3mb atm, but that;s still a lot of lines.

**Comment by GrahamCampbell** [comment]
Also, my server doesn't have a 100gb disk, lol.

**Comment by joecohens** [comment]
LOL

**Comment by GrahamCampbell** [comment]
I wonder, do i need brackets in the while statement?

**Comment by GrahamCampbell** [comment]
```php
while ($tries = count($exceptions) < 3)
```

Is php making tries a boolean, and it's false the first time, so we break on the first iteration?

**Comment by joecohens** [comment]
I think you do

**Comment by GrahamCampbell** [comment]
Hmm, so I'll need to bracket the assignment:
```php
while (($tries = count($exceptions)) < 3)
```

**Comment by GrahamCampbell** [comment]
I'll try editing the file on the server, lol.

**Comment by joecohens** [comment]
Lol I did that with Cachet to enable de debugger.

**Comment by GrahamCampbell** [comment]
Meh, that wasn't it. It's still broken.

**Comment by joecohens** [comment]
Did you replace all of them?

**Comment by GrahamCampbell** [comment]
Yeh. Hmmmmm.

**Comment by GrahamCampbell** [comment]
what's wrong with this?

https://i.starbs.net/Awl2

**Comment by joecohens** [comment]
```php

$exceptions = 0;

while (($tries = $exceptions) < 3) {
      var_dump($tries);
      $exceptions++;
}

```

int(0)
int(1)
int(2)

**Comment by joecohens** [comment]
```php

$exceptions = 0;

while ($tries = $exceptions < 3) {
      var_dump($tries);
      $exceptions++;
}

```

bool(true)
bool(true)
bool(true)

**Comment by GrahamCampbell** [comment]
Hmm, ok, I'll put them back in. I think I know what;s going on now.

**Comment by GrahamCampbell** [comment]
I must have messed up the imports so we're hitting the last catch block and breaking..

**Comment by GrahamCampbell** [comment]
Maybe i'm not allowed to catch interfaces?

**Comment by joecohens** [comment]
I think you are allowed

**Comment by GrahamCampbell** [comment]
Yeh, just checked: http://3v4l.org/sD02Y.

**Comment by GrahamCampbell** [comment]
Apart from php 5.0.0, lol.

**Comment by joecohens** [comment]
LOL

**Comment by GrahamCampbell** [comment]
Hmm, I'm going to have to add some more dumping into the logs...

**Comment by GrahamCampbell** [comment]
lol - the log is 24mb now...

**Comment by joecohens** [comment]
Lol the workers log too fast

**Comment by GrahamCampbell** [comment]
https://i.starbs.net/A6V9

**Comment by GrahamCampbell** [comment]
How can that be happening???

**Comment by GrahamCampbell** [comment]
We do have 3 exceptions though, so we know we're just hitting that 3 times and exiting, which is a start.

**Comment by joecohens** [comment]
That's weird, I'm updating my local env now to test.

**Comment by GrahamCampbell** [comment]
Yeh, why isn't deleting working? Is it possible the symfony component broke?

**Comment by joecohens** [comment]
Can you clear that dir?

**Comment by GrahamCampbell** [comment]
> Can you clear that dir?

What do you mean?

**Comment by joecohens** [comment]
I have a staging server installing StyleCI there.

**Comment by GrahamCampbell** [comment]
k :)

**Comment by GrahamCampbell** [comment]
I'll be useful to set the mail mode to pretend btw. :)

**Comment by joecohens** [comment]
> What do you mean?

I think you have it's not deleting the repo if it has already tryied

**Comment by joecohens** [comment]
Haha yeah we need a dev env setup.

**Comment by GrahamCampbell** [comment]
Oh yeh. I'm dump, lol. :)

**Comment by GrahamCampbell** [comment]
So dump I spelt it wrong the first time...

**Comment by joecohens** [comment]
Haha :)

**Comment by GrahamCampbell** [comment]
Hmmm. http://3v4l.org/7AkEf

**Comment by GrahamCampbell** [comment]
http://3v4l.org/f7h2t

**Comment by GrahamCampbell** [comment]
We seem to be calling deleted 2 times, which is correct, so it's not that. :/

**Comment by joecohens** [comment]
Still the same error?

**Comment by GrahamCampbell** [comment]
Yeh, I haven't changed the code. I just checked it's behaviour, and it was already calling delete correctly.

**Comment by GrahamCampbell** [comment]
Symfony should throw an exception if it can't be removed: https://github.com/symfony/symfony/blob/v2.6.3/src/Symfony/Component/Filesystem/Filesystem.php#L150.

**Comment by GrahamCampbell** [comment]
Exists must be returning false. :/

**Comment by joecohens** [comment]
This is weird, I feel like we're missing a dumb thing.

**Comment by GrahamCampbell** [comment]
https://i.starbs.net/e4VW

**Comment by GrahamCampbell** [comment]
Whatttt?????????????

**Comment by GrahamCampbell** [comment]
Oh wait, notepad++ was showing the old log...

**Comment by joecohens** [comment]
That brach doesn't exists anymore

**Comment by joecohens** [comment]
Haha I was going to ask you that

**Comment by joecohens** [comment]
http://styleci.dinkbitlabs.com I'm going to install it there.

Got to go for a while brb. Let me know any updates!

**Comment by joecohens** [comment]
http://styleci.dinkbitlabs.com I'm going to install it there.

Got to go for a while brb. Let me know any updates!

**Comment by GrahamCampbell** [comment]
It seems delete never actually worked. I need to pass an array to it, not a string. Symfony's phpdoc was wrong...

**Comment by GrahamCampbell** [comment]
Damn, that wasn't it. :/

**Comment by GrahamCampbell** [comment]
Fixed it. The problem was very funny....

**Comment by GrahamCampbell** [comment]
https://github.com/StyleCI/Git/commit/d1fc3696254345f0050f44fb0a0339954c33e04a

**Comment by GrahamCampbell** [comment]
That was returning false because in order to damage the repo, I deleted that folder, but then we were reporting the repo didn't exist and didn't need clearing...

**Comment by joecohens** [comment]
Awesome!! Haha told you it was a small hidden thing fix :)

**Comment by GrahamCampbell** [comment]
:)

**Pull request merged**
